//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineMaster.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Compra = new HashSet<Compra>();
        }


        public int Cliente_ID { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Email { get; set; }
        public string Nro_Tarjeta { get; set; }
        public string Contrasenia { get; set; }
        public string Dni_Cliente { get; set; }
        public string Logeado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
    }
}
