//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int Compra_ID { get; set; }
        public int Entrada { get; set; }
        public int Cliente { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Entrada Entrada1 { get; set; }
    }
}
