//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entrada()
        {
            this.Compra = new HashSet<Compra>();
        }
    
        public int Entrada_ID { get; set; }
        public string Asiento { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public int Sala { get; set; }
        public int Pelicula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual Pelicula Pelicula1 { get; set; }
        public virtual Sala Sala1 { get; set; }
    }
}
